In [35]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [36]:
df = pd.read_csv("/Users/sakshamchauhan/Downloads/Machine-Learning/Machine_Learning/NLP/Lecture-2/train.txt", sep = ';', header = None, names = ['text','emotion'])

In [37]:
df.head(10)

                                                text   emotion
0                            i didnt feel humiliated   sadness
1  i can go from feeling so hopeless to so damned...   sadness
2   im grabbing a minute to post i feel greedy wrong     anger
3  i am ever feeling nostalgic about the fireplac...      love
4                               i am feeling grouchy     anger
5  ive been feeling a little burdened lately wasn...   sadness
6  ive been taking or milligrams or times recomme...  surprise
7  i feel as confused about life as a teenager or...      fear
8  i have been with petronas for years i feel tha...       joy
9                                i feel romantic too      love

In [38]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [39]:
unique_emotion = df['emotion'].unique()
emotion_number = {}
i = 0
for emo in unique_emotion:
    emotion_number[emo] = i
    i+=1
    
df['emotion'] = df['emotion'].map(emotion_number)

In [40]:
df['text']

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: str

In [41]:
df['emotion']

0        0
1        0
2        1
3        2
4        1
        ..
15995    0
15996    0
15997    5
15998    1
15999    0
Name: emotion, Length: 16000, dtype: int64

In [42]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [43]:
df['text']

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: str

In [44]:
import string
def remove_punctuation(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [45]:
df['text'] = df['text'].apply(remove_punctuation)

In [46]:
df['text']

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: str

In [47]:
def remove_num(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new
    
df['text'] = df['text'].apply(remove_num)

In [48]:
df['text']

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: str

In [49]:
def remove_emoji(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new
    
df['text'] = df['text'].apply(remove_emoji)

In [50]:
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [51]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/sakshamchauhan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/sakshamchauhan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [52]:
stop_words = set(stopwords.words('english'))
print(stop_words)

{'about', 'how', 'to', 'where', 'doesn', "shouldn't", 'is', "she's", 'any', 'an', "needn't", 'haven', 'more', 'mightn', 'when', 'over', 'aren', "couldn't", 'which', 'wasn', "hadn't", 'needn', 'my', 'am', 'as', 'few', 'such', 'very', "you've", "we'd", 'being', 'o', "isn't", 'for', 'weren', "weren't", 'against', 'with', 'above', 'between', "she'll", "should've", 'shouldn', 'them', 'no', 'has', 'after', "she'd", 'if', 'ourselves', 'their', 'then', "you'd", 'doing', 'those', "i'm", 'in', 'isn', 'but', 'both', 'have', "we'll", 'own', 'd', 'me', "you're", 'him', 'having', 'by', "don't", 'been', 'a', 'and', 'ma', 'shan', 'myself', 'theirs', 'through', 'whom', 'you', "haven't", 'yourself', 'during', 'other', 'ain', "i'd", 'hers', 'only', 'she', "it's", 'that', 'wouldn', 'your', "doesn't", "i'll", 'her', 've', "we've", "aren't", 'will', 'couldn', 'once', 'won', 'the', 'not', 'until', 'at', 'we', 'same', 'there', 's', "he'd", 'he', 'than', 'from', 'all', 'so', 'hasn', 'be', 'y', 'don', 'now', "they'd", 'each', 'again', 'off', 'himself', 'hadn', 'out', 'it', 'this', 'or', 'too', 'yours', "it'd", 'herself', 'itself', 'can', 'was', 'most', 'themselves', 'ours', 'i', 'on', 'some', 'his', "it'll", 'do', 'these', "you'll", 'did', "wasn't", 'had', 'should', "that'll", 'below', 'yourselves', 'under', 'because', 'down', 'while', 'they', 'before', 'why', 'here', "he's", 'm', 're', 'its', 'up', 'were', "hasn't", 'didn', 'mustn', 'into', 'does', "we're", "he'll", "they've", "shan't", 't', "i've", "mightn't", "mustn't", "won't", "wouldn't", 'what', 'our', 'who', 'just', 'are', 'further', "they're", "didn't", 'of', "they'll", 'll', 'nor'}

In [53]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [54]:
def remove(txt):
    words = txt.split()
    cleaned = []

    for i in words:
        if i not in stop_words:
            cleaned.append(i)

    return ' '.join(cleaned)

df['text'] = df['text'].apply(remove)

In [55]:
df['text']

0                                    didnt feel humiliated
1        go feeling hopeless damned hopeful around some...
2                im grabbing minute post feel greedy wrong
3        ever feeling nostalgic fireplace know still pr...
4                                          feeling grouchy
                               ...
15995        brief time beanbag said anna feel like beaten
15996    turning feel pathetic still waiting tables sub...
15997                             feel strong good overall
15998                       feel like rude comment im glad
15999                         know lot feel stupid portray
Name: text, Length: 16000, dtype: str

In [56]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [57]:
from sklearn.feature_extraction.text import CountVectorizer

In [58]:
doc = [
    "I Love Pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

vectorizer = CountVectorizer(ngram_range= (1,3))

X = vectorizer.fit_transform(doc)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("\nBoW Matrix:\n", X.toarray())

Vocabulary: ['best' 'great' 'is' 'is great' 'is the' 'is the best' 'love' 'love pasta'
 'love pizza' 'pasta' 'pasta is' 'pasta is great' 'pizza' 'pizza is'
 'pizza is the' 'the' 'the best']

BoW Matrix:
 [[0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0]
 [1 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0]]

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf_vectorizer = TfidfVectorizer(ngram_range= (1,1))

X = tf_vectorizer.fit_transform(doc)

print("Vocabulary:", tf_vectorizer.get_feature_names_out())
print("\nTf_Idf Matrix:\n", X.toarray())

Vocabulary: ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

Tf_Idf Matrix:
 [[0.         0.         0.         0.70710678 0.         0.70710678
  0.        ]
 [0.55528266 0.         0.43779123 0.         0.         0.43779123
  0.55528266]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.66767854 0.52640543 0.         0.52640543 0.
  0.        ]]

In [60]:
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# 1. Split RAW TEXT and LABEL together
X_train, X_test, y_train, y_test = train_test_split(
    df["text"],
    df["emotion"],
    test_size=0.2,
    random_state=42
)

print(len(X_train))
print(len(y_train))

12800
12800

# MultiNB + BoW

In [62]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Create CountVectorizer
bow_vectorizer = CountVectorizer()

# 2. Fit on training text and transform it
X_train_bow = bow_vectorizer.fit_transform(X_train)

# 3. Transform test text using the SAME vectorizer
X_test_bow = bow_vectorizer.transform(X_test)

print(X_train_bow.shape)
print(X_test_bow.shape)

# 4. Create Naive Bayes model
MNB_model = MultinomialNB()

# 5. Train
MNB_model.fit(X_train_bow, y_train)

# 6. Predict
pred_bow = MNB_model.predict(X_test_bow)

# 7. Evaluate
print("Accuracy:", accuracy_score(y_test, pred_bow))
print(classification_report(y_test, pred_bow))
print(confusion_matrix(y_test, pred_bow))

(12800, 13361)
(3200, 13361)
Accuracy: 0.768125
              precision    recall  f1-score   support

           0       0.75      0.95      0.84       946
           1       0.89      0.63      0.74       427
           2       0.93      0.27      0.41       296
           3       1.00      0.05      0.10       113
           4       0.85      0.57      0.68       397
           5       0.73      0.96      0.83      1021

    accuracy                           0.77      3200
   macro avg       0.86      0.57      0.60      3200
weighted avg       0.80      0.77      0.74      3200

[[899   8   3   0   4  32]
 [ 87 271   0   0  13  56]
 [ 51   6  79   0   4 156]
 [ 40   0   1   6  17  49]
 [ 87  15   0   0 226  69]
 [ 36   4   2   0   2 977]]

# MultiNB + TFIDF

In [63]:
# 1. Create CountVectorizer
tfidf_vectorizer = TfidfVectorizer()

# 2. Fit on training text and transform it
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

# 3. Transform test text using the SAME vectorizer
X_test_tfidf = tfidf_vectorizer.transform(X_test)

print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

# 4. Create Naive Bayes model
MNB_tfidf_model = MultinomialNB()

# 5. Train
MNB_tfidf_model.fit(X_train_tfidf, y_train)

# 6. Predict
pred_tfidf = MNB_tfidf_model.predict(X_test_tfidf)

# 7. Evaluate
print("Accuracy:", accuracy_score(y_test, pred_tfidf))
print(classification_report(y_test, pred_bow))
print(confusion_matrix(y_test, pred_bow))

(12800, 13361)
(3200, 13361)
Accuracy: 0.6609375
              precision    recall  f1-score   support

           0       0.75      0.95      0.84       946
           1       0.89      0.63      0.74       427
           2       0.93      0.27      0.41       296
           3       1.00      0.05      0.10       113
           4       0.85      0.57      0.68       397
           5       0.73      0.96      0.83      1021

    accuracy                           0.77      3200
   macro avg       0.86      0.57      0.60      3200
weighted avg       0.80      0.77      0.74      3200

[[899   8   3   0   4  32]
 [ 87 271   0   0  13  56]
 [ 51   6  79   0   4 156]
 [ 40   0   1   6  17  49]
 [ 87  15   0   0 226  69]
 [ 36   4   2   0   2 977]]

# Logistic + TFIDF

In [34]:
from sklearn.linear_model import LogisticRegression

# 1. Create CountVectorizer
tfidf_vectorizer = TfidfVectorizer()

# 2. Fit on training text and transform it
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

# 3. Transform test text using the SAME vectorizer
X_test_tfidf = tfidf_vectorizer.transform(X_test)

print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

# 4. Create Logistic Regression model
LR_tfidf_model = LogisticRegression(max_iter=5000)

# 5. Train
LR_tfidf_model.fit(X_train_tfidf, y_train)

# 6. Predict
pred_tfidf = LR_tfidf_model.predict(X_test_tfidf)

# 7. Evaluate
print("Accuracy:", accuracy_score(y_test, pred_tfidf))
print(classification_report(y_test, pred_bow))
print(confusion_matrix(y_test, pred_bow))

(12800, 13361)
(3200, 13361)
Accuracy: 0.8628125
              precision    recall  f1-score   support

           0       0.75      0.95      0.84       946
           1       0.89      0.63      0.74       427
           2       0.93      0.27      0.41       296
           3       1.00      0.05      0.10       113
           4       0.85      0.57      0.68       397
           5       0.73      0.96      0.83      1021

    accuracy                           0.77      3200
   macro avg       0.86      0.57      0.60      3200
weighted avg       0.80      0.77      0.74      3200

[[899   8   3   0   4  32]
 [ 87 271   0   0  13  56]
 [ 51   6  79   0   4 156]
 [ 40   0   1   6  17  49]
 [ 87  15   0   0 226  69]
 [ 36   4   2   0   2 977]]